#!/bin/bash

. config/options $1 $2 $3

if [ -z "$4" ]; then
  echo "Использование: $0 package_name package_group package_repos package_release"
  exit 1
fi

if [ "$PKG_FOUND" == "no" ]; then
  printf "${boldred}$1: packages.mk файл не найден${endcolor}\n"
  exit 1
fi

PKG_RELEASE=$4

# Рабочая папка
WORK_DIR=$PKG_NAME-$(get_full_version)

# Создаем архив исходников
printf "%${BUILD_INDENT}c ${blue}Создание оригинального tar ...${endcolor}\n" ' '
FVERSION=$(get_file_version)~$PKG_RELEASE
cd $PKG_BUILD/$PKG_RELEASE
tar -czf ${PKG_NAME}_${FVERSION}.orig.tar.gz $WORK_DIR/

# Копируем файлы debian для соответствующего релиза
cp -R $PKG_DIR/debian/$PKG_RELEASE $PKG_BUILD/$PKG_RELEASE/$WORK_DIR/debian

CVERSION=$(get_change_version)~$PKG_RELEASE

# Изменяем changelog
printf "%${BUILD_INDENT}c ${blue}Изменение changelog ...${endcolor}\n" ' '
cd $PKG_BUILD/$PKG_RELEASE/$WORK_DIR/debian
CUR_DATE_CHANGELOG=`date -R`
PREFVER=$(get_pref_sources)$(get_rev_sources)
rm -f changelog
touch changelog
cat >>changelog << MYDATA
$PKG_NAME ($CVERSION) $PKG_RELEASE; urgency=high

    * [$PREFVER]

 -- $MAINTAINER  $CUR_DATE_CHANGELOG

MYDATA
